#!/bin/bash

# Read conf file from same location as script
_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. $_SCRIPT_DIR/rnsupdate.conf


debugEcho () {
  [[ "$debug" ]] && builtin echo $@ >&2
}

_usage(){
  echo "Usage: $(basename $0) [--hostname home.example.com] [--ipAddress 192.168.1.1] [--forceUpdate]"
}

_setArgs(){
  while [ "$1" != "" ]; do
    case $1 in
      "-h" | "--hostname")
        debugEcho $1 $2
        shift
        hostname=$1
        ;;
      "-i" | "--ipAddress")
        debugEcho $1 $2
        shift
        ipAddress=$1
        ;;
      "-f" | "--forceUpdate")
        debugEcho $1
        forceUpdate=true
        ;;
      "--help")
        debugEcho $1
        _usage
        exit 0
        ;;
      "-d" | "--debug")
        debug=true
        debugEcho $1
        ;;
    esac
    shift
  done
  
  debugEcho "Args read."
}

# Test an IP address for validity:
# Usage:
#      valid_ip IP_ADDRESS
#      if [[ $? -eq 0 ]]; then echo good; else echo bad; fi
#   OR
#      if valid_ip IP_ADDRESS; then echo good; else echo bad; fi
#
function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

# Test hostname for validity:
function valid_hostname()
{
    local  hostname=$1
    local  stat=1

    [[ $hostname =~ ${DDNS_ZONE}$ ]]
    stat=$?
    
    return $stat
}



ipcheckURL='https://api.ipify.org'

_getMyPublicIP(){
  local command="/usr/bin/curl -sS $ipcheckURL"
  debugEcho $command
  local ip=$($command)
  debugEcho $ip
  echo $ip
}

_getMyHostname(){
  local command="/bin/hostname"
  debugEcho $command
  local hostname=$($command)
  debugEcho $hostname
  echo $hostname
}

_getCurrentDNS(){
  local command="/usr/bin/dig +noall +answer +short $1"
  debugEcho $command
  local currentDDNS=$($command)
  debugEcho $currentDDNS
  echo $currentDDNS
}

_updateDNS(){
  local hostname=$1
  local ipAddress=$2
  
  $NSUPDATE_COMMAND <<EOF
server ${DNS_SERVER}
zone ${DDNS_ZONE}
del ${hostname} A
add ${hostname} 0 A ${ipAddress}
send
quit
EOF
}

_setArgs $*

# if not set on command line, get using the default methods
[ -z "$hostname" ] && hostname=$(_getMyHostname)
[ -z "$ipAddress" ] && ipAddress=$(_getMyPublicIP)

# get the current value set in DNS
currentDNS=$(_getCurrentDNS $hostname)

errors=0

if ! valid_hostname $hostname
then
  ((errors++))
  echo Hostname not in DDNS Zone: $hostname
fi

if ! valid_ip $ipAddress
then
  ((errors++))
  echo Invalid IP Address: $ipAddress
fi

if [[ $errors -ne 0 ]]
then
  exit $errors
fi

# decide if an update is necessary
if ( ! [ -z "$forceUpdate" ] ) || \
    [ -z "$currentDNS" ] || \
    [ "$currentDNS" != "$ipAddress" ]
then
  _updateDNS $hostname $ipAddress
fi